// <auto-generated />
using System;
using Abig2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abig2025.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222191643_FeaturesAdd")]
    partial class FeaturesAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Abig2025.Models.Location.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCodePrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Name", "ProvinceId")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Abig2025.Models.Location.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Code = "AR",
                            Name = "Argentina",
                            isActive = true
                        },
                        new
                        {
                            CountryId = 2,
                            Code = "UY",
                            Name = "Uruguay",
                            isActive = true
                        },
                        new
                        {
                            CountryId = 3,
                            Code = "CL",
                            Name = "Chile",
                            isActive = true
                        });
                });

            modelBuilder.Entity("Abig2025.Models.Location.Neighborhood", b =>
                {
                    b.Property<int>("NeighborhoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NeighborhoodId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostalCodePrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("NeighborhoodId");

                    b.HasIndex("CityId");

                    b.HasIndex("Name", "CityId")
                        .IsUnique();

                    b.ToTable("Neighborhoods");
                });

            modelBuilder.Entity("Abig2025.Models.Location.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            Code = "BA",
                            CountryId = 1,
                            Name = "Buenos Aires",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 2,
                            Code = "CA",
                            CountryId = 1,
                            Name = "Catamarca",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 3,
                            Code = "CH",
                            CountryId = 1,
                            Name = "Chaco",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 4,
                            Code = "CT",
                            CountryId = 1,
                            Name = "Chubut",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 5,
                            Code = "CB",
                            CountryId = 1,
                            Name = "Córdoba",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 6,
                            Code = "CR",
                            CountryId = 1,
                            Name = "Corrientes",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 7,
                            Code = "ER",
                            CountryId = 1,
                            Name = "Entre Ríos",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 8,
                            Code = "FO",
                            CountryId = 1,
                            Name = "Formosa",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 9,
                            Code = "JY",
                            CountryId = 1,
                            Name = "Jujuy",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 10,
                            Code = "LP",
                            CountryId = 1,
                            Name = "La Pampa",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 11,
                            Code = "LR",
                            CountryId = 1,
                            Name = "La Rioja",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 12,
                            Code = "MZ",
                            CountryId = 1,
                            Name = "Mendoza",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 13,
                            Code = "MI",
                            CountryId = 1,
                            Name = "Misiones",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 14,
                            Code = "NQ",
                            CountryId = 1,
                            Name = "Neuquén",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 15,
                            Code = "RN",
                            CountryId = 1,
                            Name = "Río Negro",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 16,
                            Code = "SA",
                            CountryId = 1,
                            Name = "Salta",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 17,
                            Code = "SJ",
                            CountryId = 1,
                            Name = "San Juan",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 18,
                            Code = "SL",
                            CountryId = 1,
                            Name = "San Luis",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 19,
                            Code = "SC",
                            CountryId = 1,
                            Name = "Santa Cruz",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 20,
                            Code = "SF",
                            CountryId = 1,
                            Name = "Santa Fe",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 21,
                            Code = "SE",
                            CountryId = 1,
                            Name = "Santiago del Estero",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 22,
                            Code = "TF",
                            CountryId = 1,
                            Name = "Tierra del Fuego",
                            isActive = true
                        },
                        new
                        {
                            ProvinceId = 23,
                            Code = "TM",
                            CountryId = 1,
                            Name = "Tucumán",
                            isActive = true
                        });
                });

            modelBuilder.Entity("Abig2025.Models.Properties.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.FeatureDefinition", b =>
                {
                    b.Property<int>("FeatureDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureDefinitionId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("FeatureDefinitionId");

                    b.ToTable("FeatureDefinitions");

                    b.HasData(
                        new
                        {
                            FeatureDefinitionId = 1,
                            DisplayName = "Permite mascotas",
                            DisplayOrder = 1,
                            Group = "Mascotas",
                            Icon = "bi bi-heart",
                            IsActive = true,
                            Key = "PermiteMascotas",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 2,
                            DisplayName = "Acceso discapacitados",
                            DisplayOrder = 10,
                            Group = "Generales",
                            Icon = "bi bi-person-bounding-box",
                            IsActive = true,
                            Key = "AccesoDiscapacitados",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 3,
                            DisplayName = "Apto profesional",
                            DisplayOrder = 11,
                            Group = "Generales",
                            Icon = "bi bi-briefcase",
                            IsActive = true,
                            Key = "AptoProfesional",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 4,
                            DisplayName = "Uso comercial",
                            DisplayOrder = 12,
                            Group = "Generales",
                            Icon = "bi bi-shop",
                            IsActive = true,
                            Key = "UsoComercial",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 5,
                            DisplayName = "Parrilla",
                            DisplayOrder = 20,
                            Group = "Amenities",
                            Icon = "bi bi-fire",
                            IsActive = true,
                            Key = "Parrilla",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 6,
                            DisplayName = "Quincho",
                            DisplayOrder = 21,
                            Group = "Amenities",
                            Icon = "bi bi-fire",
                            IsActive = true,
                            Key = "Quincho",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 7,
                            DisplayName = "Gimnasio",
                            DisplayOrder = 22,
                            Group = "Amenities",
                            Icon = "bi bi-activity",
                            IsActive = true,
                            Key = "Gimnasio",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 8,
                            DisplayName = "Solarium",
                            DisplayOrder = 23,
                            Group = "Amenities",
                            Icon = "bi bi-sun",
                            IsActive = true,
                            Key = "Solarium",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 9,
                            DisplayName = "Hidromasaje",
                            DisplayOrder = 24,
                            Group = "Amenities",
                            Icon = "bi bi-droplet",
                            IsActive = true,
                            Key = "Hidromasaje",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 10,
                            DisplayName = "Sauna",
                            DisplayOrder = 25,
                            Group = "Amenities",
                            Icon = "bi bi-thermometer-sun",
                            IsActive = true,
                            Key = "Sauna",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 11,
                            DisplayName = "Pista deportiva",
                            DisplayOrder = 26,
                            Group = "Amenities",
                            Icon = "bi bi-trophy",
                            IsActive = true,
                            Key = "PistaDeportiva",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 12,
                            DisplayName = "Sala de juegos",
                            DisplayOrder = 27,
                            Group = "Amenities",
                            Icon = "bi bi-joystick",
                            IsActive = true,
                            Key = "SalaJuegos",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 13,
                            DisplayName = "Aire acondicionado",
                            DisplayOrder = 30,
                            Group = "Confort",
                            Icon = "bi bi-snow",
                            IsActive = true,
                            Key = "AireAcondicionado",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 14,
                            DisplayName = "Caldera",
                            DisplayOrder = 31,
                            Group = "Confort",
                            Icon = "bi bi-thermometer-high",
                            IsActive = true,
                            Key = "Caldera",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 15,
                            DisplayName = "Termotanque",
                            DisplayOrder = 32,
                            Group = "Confort",
                            Icon = "bi bi-droplet-half",
                            IsActive = true,
                            Key = "Termotanque",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 16,
                            DisplayName = "Lavavajillas",
                            DisplayOrder = 33,
                            Group = "Confort",
                            Icon = "bi bi-cup-straw",
                            IsActive = true,
                            Key = "Lavavajillas",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 17,
                            DisplayName = "Alarma",
                            DisplayOrder = 34,
                            Group = "Confort",
                            Icon = "bi bi-shield-lock",
                            IsActive = true,
                            Key = "Alarma",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 18,
                            DisplayName = "Amueblado",
                            DisplayOrder = 40,
                            Group = "Interiores",
                            Icon = "bi bi-house-door",
                            IsActive = true,
                            Key = "Amueblado",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 19,
                            DisplayName = "Cocina equipada",
                            DisplayOrder = 41,
                            Group = "Interiores",
                            Icon = "bi bi-egg-fried",
                            IsActive = true,
                            Key = "CocinaEquipada",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 20,
                            DisplayName = "Lavadero",
                            DisplayOrder = 42,
                            Group = "Interiores",
                            Icon = "bi bi-bucket",
                            IsActive = true,
                            Key = "Lavadero",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 21,
                            DisplayName = "Baulera",
                            DisplayOrder = 43,
                            Group = "Interiores",
                            Icon = "bi bi-box",
                            IsActive = true,
                            Key = "Baulera",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 22,
                            DisplayName = "Toilette",
                            DisplayOrder = 44,
                            Group = "Interiores",
                            Icon = "bi bi-door-open",
                            IsActive = true,
                            Key = "Toilette",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 23,
                            DisplayName = "Balcón",
                            DisplayOrder = 45,
                            Group = "Interiores",
                            Icon = "bi bi-layout-sidebar-inset",
                            IsActive = true,
                            Key = "Balcon",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 24,
                            DisplayName = "Terraza",
                            DisplayOrder = 46,
                            Group = "Interiores",
                            Icon = "bi bi-layers",
                            IsActive = true,
                            Key = "Terraza",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 25,
                            DisplayName = "Patio",
                            DisplayOrder = 47,
                            Group = "Interiores",
                            Icon = "bi bi-tree",
                            IsActive = true,
                            Key = "Patio",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 26,
                            DisplayName = "Jardín",
                            DisplayOrder = 48,
                            Group = "Interiores",
                            Icon = "bi bi-flower1",
                            IsActive = true,
                            Key = "Jardin",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 27,
                            DisplayName = "Internet / WiFi",
                            DisplayOrder = 50,
                            Group = "Servicios",
                            Icon = "bi bi-wifi",
                            IsActive = true,
                            Key = "InternetWifi",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 28,
                            DisplayName = "Ascensor",
                            DisplayOrder = 51,
                            Group = "Servicios",
                            Icon = "bi bi-arrow-up",
                            IsActive = true,
                            Key = "Ascensor",
                            Scope = 1,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 29,
                            DisplayName = "Vigilancia",
                            DisplayOrder = 52,
                            Group = "Servicios",
                            Icon = "bi bi-eye",
                            IsActive = true,
                            Key = "Vigilancia",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 30,
                            DisplayName = "Servicio de limpieza",
                            DisplayOrder = 53,
                            Group = "Servicios",
                            Icon = "bi bi-stars",
                            IsActive = true,
                            Key = "Limpieza",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 31,
                            DisplayName = "Agua",
                            DisplayOrder = 54,
                            Group = "Servicios",
                            Icon = "bi bi-droplet",
                            IsActive = true,
                            Key = "Agua",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 32,
                            DisplayName = "Electricidad",
                            DisplayOrder = 55,
                            Group = "Servicios",
                            Icon = "bi bi-lightning",
                            IsActive = true,
                            Key = "Electricidad",
                            Scope = 0,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 33,
                            DisplayName = "Molino",
                            DisplayOrder = 60,
                            Group = "Campo",
                            Icon = "bi bi-wind",
                            IsActive = true,
                            Key = "Campo_Molino",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 34,
                            DisplayName = "Manga",
                            DisplayOrder = 61,
                            Group = "Campo",
                            Icon = "bi bi-diagram-3",
                            IsActive = true,
                            Key = "Campo_Manga",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 35,
                            DisplayName = "Cargador",
                            DisplayOrder = 62,
                            Group = "Campo",
                            Icon = "bi bi-truck",
                            IsActive = true,
                            Key = "Campo_Cargador",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 36,
                            DisplayName = "Alambrado",
                            DisplayOrder = 63,
                            Group = "Campo",
                            Icon = "bi bi-border",
                            IsActive = true,
                            Key = "Campo_Alambrado",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 37,
                            DisplayName = "Galpón",
                            DisplayOrder = 64,
                            Group = "Campo",
                            Icon = "bi bi-house",
                            IsActive = true,
                            Key = "Campo_Galpon",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 38,
                            DisplayName = "Sistema de riego",
                            DisplayOrder = 65,
                            Group = "Campo",
                            Icon = "bi bi-droplet",
                            IsActive = true,
                            Key = "Campo_SistemaRiego",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 39,
                            DisplayName = "Uso agrícola",
                            DisplayOrder = 66,
                            Group = "Campo",
                            Icon = "bi bi-seedling",
                            IsActive = true,
                            Key = "Campo_Agricola",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 40,
                            DisplayName = "Uso ganadero",
                            DisplayOrder = 67,
                            Group = "Campo",
                            Icon = "bi bi-cow",
                            IsActive = true,
                            Key = "Campo_Ganadero",
                            Scope = 2,
                            ValueType = 1
                        },
                        new
                        {
                            FeatureDefinitionId = 41,
                            DisplayName = "Uso mixto",
                            DisplayOrder = 68,
                            Group = "Campo",
                            Icon = "bi bi-intersect",
                            IsActive = true,
                            Key = "Campo_Mixto",
                            Scope = 2,
                            ValueType = 1
                        });
                });

            modelBuilder.Entity("Abig2025.Models.Properties.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyDraft", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DraftId");

                    b.ToTable("PropertyDrafts");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyFeature", b =>
                {
                    b.Property<int>("PropertyFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyFeatureId"));

                    b.Property<int>("FeatureDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PropertyFeatureId");

                    b.HasIndex("FeatureDefinitionId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyFeatures");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ImageId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId");

                    b.HasIndex("CityId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.ToTable("PropertyLocations");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StatusId");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyStatuses");
                });

            modelBuilder.Entity("Abig2025.Models.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesContractManagement")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPublications")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanId");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            DurationDays = 30,
                            IncludesContractManagement = false,
                            MaxPublications = 1,
                            Name = "Gratuito",
                            Price = 0m
                        },
                        new
                        {
                            PlanId = 2,
                            DurationDays = 30,
                            IncludesContractManagement = false,
                            MaxPublications = 3,
                            Name = "Destacada",
                            Price = 1000m
                        },
                        new
                        {
                            PlanId = 3,
                            DurationDays = 45,
                            IncludesContractManagement = false,
                            MaxPublications = -1,
                            Name = "Vip",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("Abig2025.Models.Subscriptions.UserSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Abig2025.Models.Users.LoginAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttemptId"));

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AttemptId");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("Abig2025.Models.Users.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Acceso completo al sistema",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Usuario estándar del sistema",
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Usuario con permisos limitados",
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("Abig2025.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("EmailVerificationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Abig2025.Models.Users.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId");

                    b.HasIndex("Dni");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Abig2025.Models.Users.UserReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewedId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewedId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("UserReviews");
                });

            modelBuilder.Entity("Abig2025.Models.Users.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Abig2025.Models.Location.City", b =>
                {
                    b.HasOne("Abig2025.Models.Location.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Abig2025.Models.Location.Neighborhood", b =>
                {
                    b.HasOne("Abig2025.Models.Location.City", "City")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Abig2025.Models.Location.Province", b =>
                {
                    b.HasOne("Abig2025.Models.Location.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.Favorite", b =>
                {
                    b.HasOne("Abig2025.Models.Properties.Property", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abig2025.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.Property", b =>
                {
                    b.HasOne("Abig2025.Models.Users.User", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyFeature", b =>
                {
                    b.HasOne("Abig2025.Models.Properties.FeatureDefinition", "FeatureDefinition")
                        .WithMany()
                        .HasForeignKey("FeatureDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abig2025.Models.Properties.Property", "Property")
                        .WithMany("Features")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureDefinition");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyImage", b =>
                {
                    b.HasOne("Abig2025.Models.Properties.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyLocation", b =>
                {
                    b.HasOne("Abig2025.Models.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Abig2025.Models.Location.Neighborhood", "Neighborhood")
                        .WithMany()
                        .HasForeignKey("NeighborhoodId");

                    b.HasOne("Abig2025.Models.Properties.Property", "Property")
                        .WithOne("Location")
                        .HasForeignKey("Abig2025.Models.Properties.PropertyLocation", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abig2025.Models.Location.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.Navigation("City");

                    b.Navigation("Neighborhood");

                    b.Navigation("Property");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.PropertyStatus", b =>
                {
                    b.HasOne("Abig2025.Models.Properties.Property", "Property")
                        .WithOne("Status")
                        .HasForeignKey("Abig2025.Models.Properties.PropertyStatus", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Abig2025.Models.Subscriptions.UserSubscription", b =>
                {
                    b.HasOne("Abig2025.Models.Subscriptions.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abig2025.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Abig2025.Models.Users.LoginAttempt", b =>
                {
                    b.HasOne("Abig2025.Models.Users.User", "User")
                        .WithMany("LoginAttempts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Abig2025.Models.Users.UserProfile", b =>
                {
                    b.HasOne("Abig2025.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Abig2025.Models.Users.UserReview", b =>
                {
                    b.HasOne("Abig2025.Models.Users.User", "Reviewed")
                        .WithMany()
                        .HasForeignKey("ReviewedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Abig2025.Models.Users.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewed");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Abig2025.Models.Users.UserRole", b =>
                {
                    b.HasOne("Abig2025.Models.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abig2025.Models.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Abig2025.Models.Location.City", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("Abig2025.Models.Location.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Abig2025.Models.Location.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Abig2025.Models.Properties.Property", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Features");

                    b.Navigation("Images");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Abig2025.Models.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Abig2025.Models.Users.User", b =>
                {
                    b.Navigation("LoginAttempts");

                    b.Navigation("Properties");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
